### ISSUE TITLE
Timeout waiting for connection from pool

### ISSUE THREAD

**Issue by mazzalab** [nf-core/circrna#114]
### Description of the bug

Hi,
I get the error in the title when I run the command line below. 
The error is this one: https://www.biostars.org/p/9590721/ but related to circrna.

What's wrong?

thanks in advance

### Command used and terminal output

```console
./nextflow run nf-core/circrna -profile docker --genome GRCh38 --input samples.csv --tool 'ciriquant' --module 'circrna_discovery' --outdir ./results_single --tool_filter 1 -r dev
```

### Relevant files

[.nextflow.log](https://github.com/nf-core/circrna/files/15097063/nextflow.log)

### System information

N E X T F L O W  ~  version 23.10.1
OS: Rocky Linux 8
Container: Docker
Version of nf-core/circrna: revision: c29124feaf [dev]

**Comment by nictru** [comment]
Hey, this seems to be a problem that is not really related to the pipeline, but a more general one. Since you provided the `--genome` parameter, nextflow tries to fetch reference genome data from an `AWS S3` bucket. This is also what the people in the Biostars discussion figured out. I can only recommend to follow the same steps which were suggested there. If the problems persist, you might want to remove the `genome` parameter and instead download the `fasta` and `gtf` files of your genome manually and pass the downloaded versions to the pipeline using the `--fasta`and `--gtf` parameters, respectively.

Keep me posted!

**Comment by mazzalab** [comment]
Hi Nico, it should be a problem in amazon or whatnot. Setting static paths, it works. Thanks for the quick reply.
