### ISSUE TITLE
Problem with star 2nd pass, Process exceeded running time limit - CIRCexplorer2

### ISSUE THREAD

**Issue by csittz** [nf-core/circrna#126]
Hi, i am trying to run the pipeline with this command, however,  i encounter this error "nv files not found on this host."  it seems STAR output the temp file to somewhere else rather than the work directory?

my command:
./nextflow run circrna -profile singularity -c mynf.config --input SS.csv --outdir SSout -work-dir work/ --module 'circrna_discovery' --tool_filter 2 --skip_trimming true --skip_fastqc true --fasta hg38.fasta --gtf gencode.v45.basic.annotation.gtf --save_reference

```
Execution cancelled -- Finishing pending tasks before exit
-[nf-core/circrna] Pipeline completed with errors-
ERROR ~ Error executing process > 'NFCORE_CIRCRNA:CIRCRNA:CIRCRNA_DISCOVERY:STAR_2ND_PASS (SS)'

Caused by:
  Process exceeded running time limit (16h)

Command executed:

  STAR \
      --genomeDir star \
      --readFilesIn input1/SS_1.merged.fastq.gz input2/SS_2.merged.fastq.gz \
      --runThreadN 8 \
      --outFileNamePrefix SS. \
      --outSAMtype BAM Unsorted \
       \
      --outSAMattrRGline 'ID:SS'  'SM:SS'  \
      --chimOutType Junctions WithinBAM --outSAMunmapped Within --outFilterType BySJout --outReadsUnmapped None --readFilesCommand zcat --sjdbFileChrStartEnd dataset.SJ.out$
...
Command exit status:
  -
Command output:
        STAR --genomeDir star --readFilesIn input1/SS_1.merged.fastq.gz input2/SS_2.merged.fastq.gz --runThreadN 8 --outFileNamePrefix SS. $
        STAR version: 2.7.10a   compiled: 2022-01-14T18:50:00-05:00 :/home/dobin/data/STAR/STARcode/STAR.master/source
  May 09 00:13:59 ..... started STAR run
  May 09 00:14:00 ..... loading genome
  May 09 00:14:43 ..... inserting junctions into the genome indices
  May 09 00:26:45 ..... started mapping

Command error:
  INFO:    Could not find any nv files on this host!

Work dir:
work/9d/685bc836c17ef132cdb98f3a558c50
```

**Comment by nictru** [comment]
Hey,
the problem here is not the `Could not find any nv files on this host!`. This only suggests that you are trying to use nvidia configuration but there is no GPU available on the host. The execution won't stop because of this and this process would not utilize GPU even if it would be correctly provided.

The problem here is `Process exceeded running time limit (16h)`. This indicates that the process did not finish within the per-process time limit of the pipeline. Please take a look at #116 for guidance.

**Comment by csittz** [comment]
@nictru  Thanks for info. The problem is that i don't have GPU.
I'm not sure why STAR use GPU for second pass while in first pass it used CPU and can run without problem.
Is there anyway to specify not too use GPU in config file?

**Comment by nictru** [comment]
Again, there is no GPU-related problem here. You will also find the same message in the logs of the first STAR pass and all the other pipeline tasks. This does not lead to failure and does not have any effect on the speed or success of the processing.
The only way to fix your problem is to increase the process-specific time limit as described in #116.

#### If you really want to remove this message
The pipeline would not print these messages if you did not explicitly request a GPU somewhere (thus, you can only disable the behavior by removing this request). A request could look something like this:
```
apptainer.runOptions = "--nv"
```
And probably similar for other containerization engines. This could be located in [any configuration file](https://www.nextflow.io/docs/latest/config.html#configuration-file).

**Comment by csittz** [comment]
thank you. i changed the config file and it seems to get pass that error.
will close this.
