### ISSUE TITLE
Not a valid path value: 'null'

### ISSUE THREAD

**Issue by guillaumecharbonnier** [nf-core/circrna#68]
### Description of the bug

Unable to complete any workflow except the "test" one. 

### Command used and terminal output

```console
nextflow run nf-core/circrna -profile test_full,docker -r dev

Error executing process > 'NFCORE_CIRCRNA:CIRCRNA:CIRCRNA_DISCOVERY:CIRCEXPLORER2_REFERENCE (null)'

Caused by:  Not a valid path value: 'null'
```

### Relevant files

[nextflow.log](https://github.com/nf-core/circrna/files/10314782/nextflow.log)

### System information

- N E X T F L O W  ~  version 22.10.4                  
- Desktop
- local     
- docker
- Ubuntu 22 LTS
- nf-core/circrna v1.0.0-g51abcba

**Comment by nictru** [comment]
This is because the [iGenomes config](https://github.com/nf-core/circrna/blob/18e580e3f81c3c37189c49033948616a773404af/conf/igenomes.config) is not up-to-date. The genome configuration which is used in the `test_full` example is not containing a `gtf` file for the configured genome `R64-1-1`. However, the version of the [iGenomes configuration that is used in the rnaSeq-Pipeline](https://github.com/nf-core/rnaseq/blob/3bec2331cac2b5ff88a1dc71a21fab6529b57a0f/conf/igenomes.config) contains the necessary files. 

I will update the iGenomes file and open a PR.
